# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iM9ceow_kM-50vDmsOk1n5UXCnp2Whwo
"""

first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
full_name = first_name + " " + last_name
print("Hello,", full_name + "! Welcome to the Python program.")